### PR TITLE
feat(field): able to save data directly without HTML event

### PR DESCRIPTION
**Pull request by qlaffont**
PR for https://github.com/fabian-hiller/modular-forms/issues/154

### CODE REVIEW

**Comment by qlaffont** [comment]
@fabian-hiller strange error on docs. Need help because currently the documentation is generated without issue.
image

image

**Comment by fabian-hiller** [comment]
Thanks for creating this PR. Currently I am very focused on my other project [Valibot](https://github.com/fabian-hiller/valibot). So don't expect a quick response to this PR, as I don't want to make such changes on the fly. Is [`setValue`](https://modularforms.dev/solid/api/setValue) a sufficient workaround for you at the moment?

**Comment by qlaffont** [comment]
Yes it's enough for our use ^^

**Comment by qlaffont** [comment]
any update on the PR ? :)

**Comment by fabian-hiller** [comment]
No, there a no updates. Why do you prefer your implementation over `setValue`?

**Comment by qlaffont** [comment]
For me it's a better DX and can reduce import in each component

**Comment by fabian-hiller** [comment]
It might cause problems if we add it to the `props` argument, since most people spread it in the `<input />` element. But adding it to the `field` feels wrong and ugly to me. Also, I would consider renaming it to `onValue` to be more consistent with the rest of the library. Furthermore, your current implementation reuses `setValue` and that goes against the modular design of the library. We try to include only what is really necessary to keep the initial bundle size small.

**Comment by qlaffont** [comment]
Okay so i will close the PR no problem !

**Comment by fabian-hiller** [comment]
This was not a final decision. I understand the reason for the PR. I have already received similar feedback and am open to compromise. I will consider this functionality when I rewrite Modular Forms in about 2 or 3 months.

**Pull request closed without merging**
