### PR TITLE
Fix redirect behavior of formAction$ in dev

### PR DESCRIPTION
**Pull request by tuurbo**
The redirect fix in https://github.com/fabian-hiller/modular-forms/commit/f3785022a59103831027f46b8f55d5d2f4dd8693 only works in prod mode. Here is a dev only fix that gets stripped out in prod.

See comment: https://github.com/fabian-hiller/modular-forms/issues/59#issuecomment-1544476176

### CODE REVIEW

**Comment by fabian-hiller** [comment]
I'll check the PR tomorrow. I won't get around to it today.

**Comment by fabian-hiller** [comment]
I am still unsure if I should merge it, as I suspect the code is not the problem. What package manager are you using? Do you have a monorepo with multiple package.json?

**Comment by tuurbo** [comment]
I'm using pnpm and it's not a mono repo, just a single package.json.

**Comment by fabian-hiller** [comment]
Interesting. Thanks for the info. I was assuming that the monorepo was the problem with me in dev. I would like to investigate this again in more detail. I'll try to get back to you here by the end of next week.

**Comment by fabian-hiller** [comment]
Sorry for not replying for so long. I will try to investigate the problem over the weekend.

**Comment by fabian-hiller** [comment]
I have now investigated the problem further. The package manager does not seem to be the problem, but Vite. I suspect that Vite contains the `AbortMessage` class multiple times in dev which is why `instanceof` cannot work. Since I want to avoid adding a workaround to our codebase, I'll wait and see what happens with this issue at Vite: https://github.com/vitejs/vite/issues/9528

**Comment by tuurbo** [comment]
No problem. Thanks for looking into it

**Comment by ciprianmacovei** [comment]
is there a onFormComplete for modular forms in qwikjs, because i really need some kind an event to make a get req after the form successfully submited.
thank u

**Comment by fabian-hiller** [comment]
I have now included this change with the latest update. Since I had made some changes to `formAction$`, it was faster for me to copy your code into the current code.

**Comment by fabian-hiller** [comment]
I mentioned you in the release notes. Thanks for your contribution!

**Pull request closed without merging**
