### PR TITLE
Rename autoFocus and noValidate props to match HTML equivalent

### PR DESCRIPTION
**Pull request by susickypavel**
More information in [#92](https://github.com/fabian-hiller/modular-forms/issues/92#issuecomment-1600780399)

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thank you for your PR. Before I merge your code, it is important for me to have clarity on what exactly the problem is. Therefore, I recommend creating an issue at SolidJS to get an answer from Ryan.

**Comment by susickypavel** [comment]
It's important that the issue comes from the nature of boolean attributes by HTML specification. It is said that boolean attributes (such as novalidate, autofocus) are `true` when they are present on the element `<input autofocus>` and represent `false` when they are missing on the element `<input />` means `autofocus` is set to `false`. If the attribute looks like this `<input autofocus="whatever value" />` it represents `true`, counterintuitively `<input autofocus="false" />` also means the attribute is `true`.

Let me clarify using a [playground](https://playground.solidjs.com/anonymous/dd0bd0af-5b39-48bb-9452-1f8d7669f235).

1. autofocus attribute

Currently, in Field props, you have a prop called `autoFocus` in camelCase. However, this prop is invalid, as you can see in the playground (line 30). It's not even typed, but this isn't caught in many cases since it is common to just spread all the props on the input element. It's correct to rename it to a lowercase version.

2. `novalidate` vs `noValidate`

This is a little bit more tricky. The interface for the form element is defined like this:

```tsx
  interface FormHTMLAttributes<T> extends HTMLAttributes<T> {
    acceptcharset?: string;
    action?: string;
    autocomplete?: string;
    encoding?: HTMLFormEncType;
    enctype?: HTMLFormEncType;
    method?: HTMLFormMethod;
    name?: string;
    novalidate?: boolean; // NOTE: Notice the lowercase version
    target?: string;
    acceptCharset?: string;
    noValidate?: boolean; // NOTE: Notice the camelCase version
 }
```

Both `novalidate` and `noValidate` seems to be working correctly and I'll report it to Ryan whether we're missing something or it's a bug.

**Comment by fabian-hiller** [comment]
Thank you very much for your detailed answer. I will merge the changes and publish them with the next version.

**Comment by susickypavel** [comment]
Thank you! I'll keep an eye on this as I suspect that the `novalidate` attribute is a little bit broken in SolidJS, I'll update you as soon as I have more information.

**Pull request merged**
