### PR TITLE
Add form submit method #130

### PR DESCRIPTION
**Pull request by katywings**
This adds the submit helper method as discussed in #130. I looked at your other commits and tried to include all things necessary from a project point of view, but let me know if something is missing ;).

P.S. I only tested the solid implementation and the website changes! Could you try out the (p)react and qwik implementations for me, if you already have the proper setup for them?
P.P.S. The changelogs include generic dates which have to be updated on release

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Thank you for your contribution! I will try to review the PR over the weekend.

**Comment by katywings** [comment]
You're welcome and thank you for the review in advance, no stress 😁👍

**Comment by fabian-hiller** [comment]
Thank you for this perfect PR! Will merge and publish it soon.

**Comment by katywings** [comment]
Awesome, thank you also for the edits :). Definitely a good idea to avoid the state-tracking sideeffects 🙏.

**Pull request merged**
